account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import signup

app_name = 'account'

urlpatterns =[
    path('signin/', LoginView.as_view(template_name='account/signin.html'), name='signin'),
    path('signout/', LogoutView.as_view(template_name='account/signout.html'), name='signout'),
    path('signup/', signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('report.urls')),
    path('account/', include('account.urls')),
]

report/urls.py
from django.urls import path

from .views import mayCalendar, event_create, event_update, event_delete, day_detail

app_name = 'report'

urlpatterns = [
    path('', mayCalendar, name='calendar'),
    path('create/<int:day_number>/', event_create, name='create'),
    path('update/<int:event_id>', event_update, name='update'),
    path('delete/<int:event_id>', event_delete, name='delete'),
    path('detail/<int:day_number>/', day_detail, name='detail'),
]

report/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Day(models.Model):
    DAY_OF_MONTH = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10),
                    (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20),
                    (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30),
                    (31, 31))
    m_day = models.PositiveSmallIntegerField(default=1, choices=DAY_OF_MONTH)

    class Meta:
        ordering = ['m_day']

    def __str__(self):
        return str(self.m_day) + "일"

    def get_absolute_url(self):
        return reverse('report:detail', args=[self.m_day])

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Event(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='events')
    f_day = models.ForeignKey(Day, on_delete=models.SET_NULL, null=True, related_name='events')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='events')
    description = models.CharField(max_length=50)
    expense = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.category.name + str(self.expense)

report/forms.py
from django import forms
from .models import Day, Category, Event

class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['category', 'description', 'expense']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].label = "분류"
        self.fields['description'].label = "내용"
        self.fields['expense'].label = "금액"
        self.fields['description'].widget.attrs = {'placeholder': "사용처 입력"}

report/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
import calendar

from .models import Day, Category, Event
from .forms import EventForm
from django.utils.safestring import mark_safe

class MayCalendar(calendar.HTMLCalendar):

    user = None

    def formatday(self, day, weekday):

        user = self.user
        t_expense = self.trans_expense(day)
        m_expense = self.meal_expense(day)
        e_expense = self.etc_expense(day)
        total_expense = self.total_expense(day)

        if day == 0:
            return '<td class="%s">&nbsp;</td>' % self.cssclass_noday
        else:
            a = 10000
            test = "{:,}".format(a)
            return '<td class="%s"><a id="day" href="/detail/%d">%d</a>' \
                   '<div id="food">%s</div>' \
                   '<div id="trans">%s</div>' \
                   '<div id="etc">%s</div>' \
                   '<div>%s</div></td>' \
                   % (self.cssclasses[weekday], day, day, m_expense, t_expense, e_expense, total_expense)

    def formatmonthname(self, theyear, themonth, withyear=True):
        """
        Return a month name as a table row.
        """
        if withyear:
            s = '%s %s' % (calendar.month_name[themonth], theyear)
        else:
            s = '%s' % calendar.month_name[themonth]
        return '<tr><th colspan="7" class="%s" id="title">%s</th></tr>' % (
            self.cssclass_month_head, s)

    def total_expense(self, day):
        event_list = Event.objects.filter(author=self.user, f_day=day)
        t_expense = 0
        for event in event_list:
            t_expense += event.expense

        if not event_list:
            t_expense = '&nbsp;'
        return t_expense

    def meal_expense(self, day):
        event_list = Event.objects.filter(f_day=day, category_id=1, author=self.user)
        meal_expense = 0
        for event in event_list:
            meal_expense += event.expense

        if not event_list:
            meal_expense = '&nbsp;'

        return str(meal_expense)

    def trans_expense(self, day):
        event_list = Event.objects.filter(f_day=day, category_id=2, author=self.user)
        trans_expense = 0
        for event in event_list:
            trans_expense += event.expense

        if not event_list:
            print(f'----------------------------{event_list}]')
            trans_expense = '&nbsp;'

        return str(trans_expense)

    def etc_expense(self, day):
        event_list = Event.objects.filter(f_day=day, category_id=3, author=self.user)
        etc_expense = 0
        for event in event_list:
            etc_expense += event.expense

        if not event_list:
            etc_expense = '&nbsp;'

        return str(etc_expense)

def mayCalendar(request):
    mayCal = MayCalendar(calendar.SUNDAY)

    user = request.user
    if user.id == None:
        user = None
    mayCal.user = user

    total_meal = calculate(user, 1)
    total_trans = calculate(user, 2)
    total_etc = calculate(user, 3)

    cal = mayCal.formatmonth(2019,5)

    context = {'object_list': mark_safe(cal),
               'total_meal':total_meal,
               'total_trans': total_trans,
               'total_etc' : total_etc,
               }
    return render(request, 'report/calendar.html', context )

@login_required
def event_create(request, day_number):
    day_info = Day.objects.get(m_day=day_number)
    event_form = EventForm(request.POST)
    event_form.instance.author_id = request.user.id
    event_form.instance.f_day = day_info

    if event_form.is_valid():
        event = event_form.save()

    return redirect(day_info)

@login_required
def event_update(request, event_id):
    event = Event.objects.get(pk=event_id)
    day_info = Day.objects.get(m_day=event.f_day.m_day)

    if request.method == "POST":
        event_form = EventForm(request.POST, instance=event)
        if event_form.is_valid():
            event_form.save()
            return redirect(day_info)
    else:
        event_form = EventForm(instance=event)

    return render(request, 'report/event_update.html', {'event_form': event_form})

@login_required
def event_delete(request, event_id):
    event = Event.objects.get(pk=event_id)
    day_info = Day.objects.get(m_day=event.f_day.m_day)

    if request.method == "POST":
        event.delete()
        return redirect(day_info)
    else:
        return render(request, 'report/event_delete.html', {'event': event})

@login_required
def day_detail(request, day_number):

    if not Day.objects.filter(m_day=day_number):
        day_info = Day()
        day_info.m_day = day_number
        day_info.save()

    day_info = Day.objects.get(m_day=day_number)

    events = Event.objects.filter(author=request.user, f_day=day_info)

    event_form = EventForm()
    return render(request, 'report/day_detail.html', {'day_info': day_info,
                                                   'event_form': event_form,
                                                   'events': events})




def calculate(user, category):

    total = 0
    event_list = Event.objects.filter(author=user, category_id=category)
    for event in event_list:
        total += event.expense

    return total

# def max(user):
#     days = Day.objects.all()
#
#     expense_list = []
#     for day in days:
#         event_list = Event.objects.filter(author=user, f_day=day)
#         total = 0
#         for event in event_list:
#             total += event.expense
#             expense_list.append(total)
#
#     day_number = expense_list.index(max(expense_list))





# def calcul2(user, category):
#
#     def total_expense(self, day):
#         event_list = Event.objects.filter(author=self.user, f_day=day)
#         t_expense = 0
#         for event in event_list:
#             t_expense += event.expense

report/templates/report/calendar.html
{% extends 'base.html' %}
{% block title %}
Calendar
{% endblock %}

{% block content %}
<style>
    .container {
      margin: 0px;
    }

    .col-4{
    background-color:#262626;
    color:#ffffff;
    }

    #login{
    color:#ffffff;
    }

    #logout{
    color:#ffffff;
    }

    #signup{
    color:#ffffff;
    }

    #title{
    text-align: center;
    background-color:#eeeeee;
    color:#000000;
    padding-top:5px;
    padding-bottom:5px;
    border-bottom: 7px outset #1ABC9C;
    font-size: 30px;
    }

    #day{
    color:#000000;
    }

<!--    #food{-->
<!--    background-color:#B71C1C;-->
<!--    border-radius: 5px / 5px;-->
<!--    color:#ffffff;-->
<!--    width:90px;-->
<!--    }-->

<!--    #trans{-->
<!--    background-color:#FF5722;-->
<!--    border-radius: 5px / 5px;-->
<!--    color:#ffffff;-->
<!--    }-->

<!--    #etc{-->
<!--    background-color:#F1C40F;-->
<!--    border-radius: 5px / 5px;-->
<!--    color:#ffffff;-->
<!--    }-->

    th{
    padding-left:70px;
    padding-right:70px;
    background-color:#eeeeee;
    }

    td{
    background-color:#eeeeee;
    padding-bottom:34px;
    }
</style>
<div class="container">
<div class="row">
    <div class="col-4">
        <div class="row" style="height:10%;background-color:#4d4d4d; color:#A6ACAF; text-align: center; padding-top:20px">
        <div class="col-12" >
          {% if user.is_authenticated %}
            안녕하세요, {{user}}님 반갑습니다.<br>
            <a id="logout" href="{% url 'account:signout' %}">로그아웃</a>
            {% else %}
            로그인해주세요.<br>
            <a id="login" href="{% url 'account:signin' %}">로그인</a>
            &nbsp;
            <a id="signup" href="{% url 'account:signup' %}">회원가입</a>
            {% endif %}
        </div>
      </div>
         <div class="row">
        <div class="col-12">
          <div id="menu">
            > 카테고리별 지출 금액 <br>
              <p>{{ total_meal }}</p>
              <p>{{ total_trans }}</p>
              <p>{{ total_etc }}</p>
            > 최대 지출 일<br>
            > 월간 기타 통계<br>
        </div>
        </div>
      </div>
    </div>
    <div class="col-8">
        {{object_list}}
    </div>
  </div>
</div>
{% endblock %}

report/templates/report/day_detail.html
{% extends 'base.html' %}
{% block title %}
Day Detail
{% endblock %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col"></div>
    <div class="col-7">
        <table class="table table-strped">
        <thead>
        <tr>
        <th colspan="10" class="align-left" style="background-color:#262626; color:#ffffff; padding-bottom:5px;"><h5>내역 추가</h5></th>
        </tr>
        </thead>
        </table>
        <form action="{% url 'report:create' day_info.m_day %}" method="post">
            {% csrf_token %}
            {{event_form.as_p}}
            <input type="submit" value="완료" class="btn btn-outline-dark btn-sm" >
        </form>
        <br>
        <div>
        {% include 'report/event_list.html' %}
        </div>
    </div>
    <div class="col">

    </div>
</div>
</div>
{% endblock %}

report/templates/report/event_delete.html
{% extends 'base.html' %}
{% block title %}
Event Delete
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <form action="" method="post">
            <div class="alert alert-danger">
                해당 지출 내역을 삭제할까요?
                &nbsp;분류 : {{event.category.name}}
                &nbsp;&nbsp;&nbsp;내용 : {{event.description}}
                &nbsp;&nbsp;&nbsp;금액 : {{event.expense}}원
            </div>
            {% csrf_token %}
            <input type="submit" value="삭제" class="btn btn-outline-danger btn-sm">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

report/templates/report/event_list.html
<style>
    #cat_name{
    background-color :#1ABC9C;
    color:#ffffff;
    padding-top:4px;
    padding-bottom:4px;
    padding-left:20px;
    padding-right:20px;
    border-radius: 50px / 50px;
    }

    .expense{
    text-align: right;
    font-weight: bold;
    color:#16A085;
    }
</style>

<table class="table table-strped">
    <thead>
    <tr>
        <th colspan="10" class="align-left" style="background-color:#1ABC9C; color:#ffffff; padding-bottom:5px;"><h5>지출 내역</h5></th>
    </tr>
    <tr>
        <th colspan="10" class="align-left">총 {{events.count}}건</th>
    </tr>
    </thead>
    {% for event in events %}
    <tr>
        <td><strong id="cat_name">{{event.category.name}}</strong></td>
        <td><strong>{{event.description}}</strong><br><small class="text-muted">{{event.created}}</small></td>
        <td><div class="expense">
            <script type="text/javascript">
            var a = "{{event.expense}}"
            function numberWithCommas(x) {
                return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
            }
            document.write(numberWithCommas(a))
            </script>원
        </div></td>
        <td>
            <a href="{% url 'report:update' event.id %}" class="btn btn-outline-dark btn-sm">수정</a>
            <a href="{% url 'report:delete' event.id %}" class="btn btn-outline-dark btn-sm">삭제</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% block extra_script %}
<script type="text/javascript">
</script>
{% endblock %}

report/templates/report/event_update.html
{% extends 'base.html' %}
{% block title %}
Event Update
{% endblock %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <form action="" method="post">
            {% csrf_token %}
            {{event_form.as_p}}
            <input type="submit" value="수정" class="btn btn-dark btn-sm">
        </form>
    </div>
    <div class="col"></div>
</div>
</div>
{% endblock %}